### ISSUE TITLE
Make 'dvc add directory' add all files inside directory

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#367]

**Comment by efiop** [comment]
Leaving for the next release.

**Comment by efiop** [comment]
Returning back to current release, as #434 made it clear that people need this feature.

**Comment by efiop** [comment]
Plus, need to add ability to add directory as a whole. Relevant for parquet scenario.

**Comment by Nicolabo** [comment]
Hi, great tool! Really appreciate it!
Few words about my project... recently I took over a ML project. Data are stored in Amazon Athena. During the data preparation process, I query data, read them to EC2, make some data manipulation. During the process, I create hundreds of csv's which store them in several directories. Thus my question: Is it possible to treat directory as dependencies or output when executing `dvc run`?

For example, I was trying to accomplish it based on your [tutorial](https://blog.dataversioncontrol.com/data-version-control-tutorial-9146715eda46). I created necessary directories, rewrite code in code/conf.py (with proper paths).

This my modified code (based on code in tutorial):

```
dvc run -d data/tgz/Posts.xml.tgz -o data/xml/ tar zxf data/tgz/Posts.xml.tgz -C data/xml/
dvc run -d data/xml/ -d code/xml_to_tsv.py -d code/conf.py -o data/tsv/ python code/xml_to_tsv.py
dvc run -d data/tsv/ -d code/split_train_test.py -d code/conf.py -o data/tt/  python code/split_train_test.py 0.33 20180319
dvc run -d code/featurization.py -d code/conf.py -d data/tt -o data/matrix_t/ python code/featurization.py
dvc run -d data/model/model.p -d data/matrix_t/matrix-test.p -d code/evaluate.py -d code/conf.py -o data/eval.txt -f Dvcfile python code/evaluate.py
```
Then, when I want to create a new branch, modified code/featurization.py,  and execute `dvc repro`, nothing happens. Like there was no changes in code.

Probably, I miss something. 

I just read about your tool few days ago and since then I am excited! Please let me know what's wrong. 

Thanks,

**Comment by Nicolabo** [comment]
Hi Ruslan,
Indeed, I had 0.9.6 version. But after upgrade, problem still exists.

this is my `dvc repro` after I checkout to new branch:

```
dvc repro -v
updater is not old enough to check for updates
Dependency 'data/eval.txt' didn't change
Dependency 'data/model/model.p' didn't change
Dependency 'data/matrix_t/matrix-test.p' didn't change
Dependency 'code/evaluate.py' didn't change
Dependency 'code/conf.py' didn't change
Dvc file 'Dvcfile' didn't change
```

I also should mention that I store Dvcfile in project directory (`.`) and all `.dvc` files in custom directory (`./dvcfiles/`). Is it right approach?

Thanks,

**Comment by efiop** [comment]
Hm, the approach is correct, as long as you adjust your commands properly.

Could you share your git repo with me somehow? So I can take a look and not bother you with a dozen of questions? ;)

**Comment by Nicolabo** [comment]
sure, you can find [here](https://github.com/Nicolabo/dvc_test)

**Comment by efiop** [comment]
Thank you!

First thing that I notice is that your dvcfiles under ./dvcfiles/ have improper paths. I.e. 
```
(python3-dvc) ➜  dvc_test git:(master) cat dvcfiles/tsv.dvc
cmd: python code/xml_to_tsv.py                             
deps:                                                      
- md5: d1cc6d9c7d0e872e93958c8dd04b411d.dir                
  path: data/xml                                           
- md5: 5b1d44d25ff148a90e6c40a1585fe68d                    
  path: code/xml_to_tsv.py                                 
- md5: b68fa555607d0399f8de130b41c6c211                    
  path: code/conf.py                                       
md5: 97a538b29de4c200578431e17e4427f2                      
outs:                                                      
- cache: true                                              
  md5: 8c0e72f83ebdc09c69ed0a17af50c62a.dir                
  path: data/tsv                                           
```

Notice how the paths are 'data/', which is not correct, as your command is being run in the same directory that your dvcfile is placed. So tsv.dvc is ran from dvcfiles/ directory, which makes your paths wrong, as they should actually be ../code/ and ../data/ . Your main Dvcfile is correct though. Could you correct that and try again?
