### ISSUE TITLE
unix relative path issue

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#613]
dvc repro failing due to some relative path issue in unix system. Same work fine in windows. Below is the error. File is placed at the correct location and related python works fine if ran independently.

![image](https://user-images.githubusercontent.com/25551691/38294776-943ead5e-3809-11e8-8b93-453d8769b213.png)

**Comment by rahulguptajss** [comment]
there seems to be some serious issues in path creation in dvc. It is not creating proper folders and looking for wrong folders as well.

for example: **(a\b)** is being treated as a file instead of folders.

![image](https://user-images.githubusercontent.com/25551691/38294868-f763fc9a-3809-11e8-8801-8b7981406276.png)

**Comment by efiop** [comment]
Ah, this happens when dvc files were created in windows, but then ran in *nix. I can confirm this bug.
Working on the solution right now...

For now, you can work around it by manually converting paths in your dvc files to *nix format, it should do the trick.

**Comment by efiop** [comment]
No, only your *.dvc files, no need to go into .dvc directory. I don't think that dos2unix converts paths inside text files, it is made to convert line breaks etc. E.g. you should convert train.p.dvc from:
```
cmd: python source/scripts/split_train_test.py
deps:                                         
- md5: 5fb9105c342df2de330913ae8e3767a7       
  path: data\CombinedSummary.csv              
- md5: 688eeb0836d7034cf1cfd53c1333ff5f       
  path: source\scripts\split_train_test.py    
outs:                                         
- cache: true                                 
  md5: 184b9aee2f5df48f1ed2cf22d3c33d07       
  path: data\train.p                          
```
to
```
cmd: python source/scripts/split_train_test.py
deps:                                         
- md5: 5fb9105c342df2de330913ae8e3767a7       
  path: data/CombinedSummary.csv              
- md5: 688eeb0836d7034cf1cfd53c1333ff5f       
  path: source/scripts/split_train_test.py    
outs:                                         
- cache: true                                 
  md5: 184b9aee2f5df48f1ed2cf22d3c33d07       
  path: data/train.p                          
```
