### ISSUE TITLE
Save datetime along with outs md5 field

### ISSUE THREAD

**Issue by prihoda** [dataversioncontrol/dvc#669]
Current datetime could be saved along with each **output** md5 field to make it easier to see which version of the file is the hash referencing.

```
cmd: wc -l input.txt > count.txt
deps: 
- md5: 3c57a863e8d24a77427a2b3dce171a4f
  path: input.txt
outs:
- cache: true
  updated: "2018-04-18 15:41:41"
  md5: f136ecf4fe2a555c1eefb51332f0f967
  path: count.txt
```
